dist: xenial
language: python
python:
  - "3.7"

cache:
  directories:
    - $HOME/.cache/pip

env:
  global:
    - ANSIBLE_HOST_KEY_CHECKING="False"
    - PIP_DOWNLOAD_CACHE="$HOME/.cache/pip"
    - OC_BINARY_URL="https://mirror.openshift.com/pub/openshift-v3/clients/3.11.133/linux/oc.tar.gz"
    - ANSIBLE_VERSION="2.7"
    - OCP_CLUSTER_URL="https://console.ci-1.cop.rht-labs.com"
    - LE_CA_CERT="https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem.txt"

before_install:
  - sudo apt-get update -qq

install:
  - pip install -U pip
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible~=$ANSIBLE_VERSION; fi
  #- pip install "ansible-lint<4.0" yamllint flake8 molecule docker "pytest<3.10" "testinfra==3.0.4"
  # Configure OpenShift Binary
  - sudo wget -qO- ${OC_BINARY_URL} | sudo tar -xvz -C /bin
  # Download Lets Encrypt CA cert
  - wget -qO le-ca-cert.pem ${LE_CA_CERT}

before_script:
  # Login to the CI cluster
  - oc login --token ${CI_CLUSTER_TOKEN} --server ${OCP_CLUSTER_URL} --certificate-authority le-ca-cert.pem
  # Run Applier to provision all of the builds
  - _test/setup.sh applier cqci-${TRAVIS_JOB_ID} ${TRAVIS_REPO_SLUG} ${TRAVIS_BRANCH}

script:
  # Test to ensure that builds all succeed
  - _test/setup.sh test cqci-${TRAVIS_JOB_ID}

after_success:
  # Delete CI project on successful completion
  - _test/setup.sh cleanup cqci-${TRAVIS_JOB_ID}

after_failure:
  - echo "Job failed and will be deleted in 12 hours."
  - echo "${TRAVIS_TEST_RESULT}"
