---
namespace: jenkins-slaves
repository_url: https://github.com/redhat-cop/containers-quickstarts.git
slave_repo_ref: v1.11
templates_repo_ref: v1.4.8

jenkins_slaves:
  build:
    ansible:
      NAME: jenkins-slave-ansible
      SOURCE_CONTEXT_DIR: jenkins-slaves/jenkins-slave-ansible
      SOURCE_REPOSITORY_REF: "{{ slave_repo_ref }}"
      SOURCE_REPOSITORY_URL: "{{ repository_url }}"
    arachni:
      NAME: jenkins-slave-arachni
      SOURCE_CONTEXT_DIR: jenkins-slaves/jenkins-slave-arachni
      SOURCE_REPOSITORY_REF: "{{ slave_repo_ref }}"
      SOURCE_REPOSITORY_URL: "{{ repository_url }}"
    python:
      NAME: jenkins-slave-python
      SOURCE_CONTEXT_DIR: jenkins-slaves/jenkins-slave-python
      SOURCE_REPOSITORY_REF: "{{ slave_repo_ref }}"
      SOURCE_REPOSITORY_URL: "{{ repository_url }}"
    golang:
      NAME: jenkins-slave-golang
      SOURCE_CONTEXT_DIR: jenkins-slaves/jenkins-slave-golang
      SOURCE_REPOSITORY_REF: "{{ slave_repo_ref }}"
      SOURCE_REPOSITORY_URL: "{{ repository_url }}"
    gradle:
      NAME: jenkins-slave-gradle
      SOURCE_CONTEXT_DIR: jenkins-slaves/jenkins-slave-gradle
      SOURCE_REPOSITORY_REF: "{{ slave_repo_ref }}"
      SOURCE_REPOSITORY_URL: "{{ repository_url }}"
    mongodb:
      NAME: jenkins-slave-mongodb
      SOURCE_CONTEXT_DIR: jenkins-slaves/jenkins-slave-mongodb
      SOURCE_REPOSITORY_REF: "{{ slave_repo_ref }}"
      SOURCE_REPOSITORY_URL: "{{ repository_url }}"
    mvn:
      NAME: jenkins-slave-mvn
      SOURCE_CONTEXT_DIR: jenkins-slaves/jenkins-slave-mvn
      SOURCE_REPOSITORY_REF: "{{ slave_repo_ref }}"
      SOURCE_REPOSITORY_URL: "{{ repository_url }}"
    npm:
      BUILDER_IMAGE_NAME: openshift/jenkins-slave-base-centos7:v3.11
      NAME: jenkins-slave-npm
      SOURCE_CONTEXT_DIR: jenkins-slaves/jenkins-slave-npm
      SOURCE_REPOSITORY_REF: "{{ slave_repo_ref }}"
      SOURCE_REPOSITORY_URL: "{{ repository_url }}"
    zap:
      BUILDER_IMAGE_NAME: centos:centos7
      NAME: jenkins-slave-zap
      SOURCE_CONTEXT_DIR: jenkins-slaves/jenkins-slave-zap
      SOURCE_REPOSITORY_REF: "{{ slave_repo_ref }}"
      SOURCE_REPOSITORY_URL: "{{ repository_url }}"

test_pipelines:
  deploy:
    golang:
      NAME: jenkins-slave-golang
      PIPELINE_CONTEXT_DIR: jenkins-slaves/jenkins-slave-golang
      PIPELINE_FILENAME: "Jenkinsfile.test"
      PIPELINE_SOURCE_REPOSITORY_REF: "{{ slave_repo_ref }}"
      PIPELINE_SOURCE_REPOSITORY_URL: "{{ repository_url }}"

openshift_cluster_content:
- object: Environment Setup
  content:
  - name: Create Projects
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/v3.9.0/files/projectrequest/template.yml"
    action: create
    params_from_vars:
      NAMESPACE: "{{ namespace }}"
      NAMESPACE_DISPLAY_NAME: "{{ namespace }}"
    tags:
      - project
- object: jenkins-ephemeral
  content:
  - name: jenkins-ephemeral
    template: 'openshift//jenkins-ephemeral'
    namespace: "{{ namespace }}"
    tags:
      - jenkins-ephemeral
- object: jenkins-slave-nodes
  content:
  - name: jenkins-slaves
    template: "{{ inventory_dir }}/../.openshift/templates/jenkins-slave-generic-template.j2"
    params_from_vars: "{{ jenkins_slaves.build }}"
    namespace: "{{ namespace }}"
    tags:
      - jenkins-slaves
- object: test-pipelines
  content:
  - name: Deploy golang-slave test pipelines
    template: "https://raw.githubusercontent.com/redhat-cop/openshift-templates/{{ templates_repo_ref }}/jenkins-pipelines/jenkins-pipeline-template-no-ocp-triggers.yml"
    params_from_vars: "{{ test_pipelines.deploy.golang }}"
    namespace: "{{ namespace }}"
    tags:
      - test-pipelines
      - golang-slave-pipeline
