name: ubi8-git-pr-ci
on:
  pull_request:
    paths:
      - ubi8-git/**
jobs:
  build:
    env:
      context: ubi8-git
    # Only build on redhat-cop repo, do not attempt to build on forks
    if: github.repository == 'pabrahamsson/containers-quickstarts'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check and verify version.json
        id: check_version
        run: |
          echo -n ::set-output name=IMAGE_TAGS::
          echo $(jq -r '.version' ${context}/version.json)
      - name: Build image and test image
        run: |
          echo "Running: docker build -f ${context}/Dockerfile -t ${context}:${{ steps.check_version.outputs.IMAGE_TAGS }} ${context}"
          docker build -f ${context}/Dockerfile -t ${context}:${{ steps.check_version.outputs.IMAGE_TAGS }} ${context}
          echo "Running: docker run ${context}:${{ steps.check_version.outputs.IMAGE_TAGS }} git --version"
          docker run ${context}:${{ steps.check_version.outputs.IMAGE_TAGS }} git --version
